# Site settings
title:       Ada Collaboration Initiative
email:
description: 'Official Site for the ACI'
url:         'https://the-aci.github.io'
baseurl:
twitter_username:
github_username:  jquorning

# Build settings
markdown: kramdown
permalink: pretty
